SOCIAL_AUTH_FACEBOOK_KEY = 'INSERT_YOUR_KEY'
SOCIAL_AUTH_FACEBOOK_SECRET = 'INSERT_YOUR_KEY'

SOCIAL_AUTH_TWITTER_KEY = 'INSERT_YOUR_KEY'
SOCIAL_AUTH_TWITTER_SECRET = 'INSERT_YOUR_KEY'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '8507...kg6.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'gUzw...CD32-'

